// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TargetWeb1.Database;

namespace TargetWeb1.Migrations
{
    [DbContext(typeof(PortalTargetDbContext))]
    partial class PortalTargetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("TargetWeb1.Models.Articulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8) CHARACTER SET utf8mb4");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4");

                    b.Property<decimal>("PrecioSugMayorista")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioSugMeLi")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioSugMinorista")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("StockEnBulto")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("StockUnidades")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4");

                    b.HasKey("Id")
                        .HasName("PK_UserGroups");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("Idx_Name");

                    b.ToTable("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
